# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2074, 907)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 70, 461, 391))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 70, 461, 341))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label888 = QtWidgets.QLabel(self.centralwidget)
        self.label888.setGeometry(QtCore.QRect(740, 510, 461, 311))
        self.label888.setText("")
        self.label888.setObjectName("label888")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(890, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(890, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(710, 0, 20, 901))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.similaritySearch = QtWidgets.QPushButton(self.centralwidget)
        self.similaritySearch.setGeometry(QtCore.QRect(260, 510, 411, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.similaritySearch.setFont(font)
        self.similaritySearch.setObjectName("similaritySearch")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 0, 20, 931))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.createDatabase = QtWidgets.QPushButton(self.centralwidget)
        self.createDatabase.setGeometry(QtCore.QRect(0, 670, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.createDatabase.setFont(font)
        self.createDatabase.setObjectName("createDatabase")
        self.defineSchema = QtWidgets.QPushButton(self.centralwidget)
        self.defineSchema.setGeometry(QtCore.QRect(0, 90, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.defineSchema.setFont(font)
        self.defineSchema.setObjectName("defineSchema")
        self.convertBase64 = QtWidgets.QPushButton(self.centralwidget)
        self.convertBase64.setGeometry(QtCore.QRect(0, 380, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.convertBase64.setFont(font)
        self.convertBase64.setObjectName("convertBase64")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(180, 660, 541, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(210, 690, 481, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1250, 50, 631, 541))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(1210, -10, 20, 901))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.PR_cal = QtWidgets.QPushButton(self.centralwidget)
        self.PR_cal.setGeometry(QtCore.QRect(1390, 700, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.PR_cal.setFont(font)
        self.PR_cal.setObjectName("PR_cal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2074, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "search   image"))
        self.label_3.setText(_translate("MainWindow", "similary  image1"))
        self.label_5.setText(_translate("MainWindow", "similary  image2"))
        self.similaritySearch.setText(_translate("MainWindow", "similarity search"))
        self.createDatabase.setText(_translate("MainWindow", "create database"))
        self.defineSchema.setText(_translate("MainWindow", "define schema"))
        self.convertBase64.setText(_translate("MainWindow", "convert base64"))
        self.PR_cal.setText(_translate("MainWindow", "presion-recall"))

